# Cloudflare Pages Configuration
# This file configures how your application is deployed to Cloudflare Pages

#:schema node_modules/wrangler/config-schema.json
name = "pom-bolt"

# Enable Node.js compatibility mode for Cloudflare Workers
compatibility_flags = ["nodejs_compat"]

# Set the compatibility date for Cloudflare Workers features
compatibility_date = "2024-10-01"

# Specify the directory containing the built client files
pages_build_output_dir = "./build/client"

# Enable metrics collection for monitoring
send_metrics = true

# D1 Database for project metadata
[[d1_databases]]
binding = "DB"
database_name = "pom-bolt-db"
database_id = "f266f4f7-7225-4f31-bcc7-c5010481f263" # Replace with your actual database ID
# The preview_database_id will be different when deployed as a preview
# database_id = "your-production-d1-database-id"

# KV Namespaces
[[kv_namespaces]]
binding = "POM_BOLT_PROJECTS"
id = "dfe2d0d711d8469298b9ebe3c4d5f596" # Replace with your actual KV namespace ID
# preview_id = "your-preview-kv-namespace-id"
# id = "your-production-kv-namespace-id"

[[kv_namespaces]]
binding = "POM_BOLT_FILES"
id = "505f6c673aa64c7dba8170749caddbdb"

[[kv_namespaces]]
binding = "POM_BOLT_CACHE"
id = "43bb1fedfd1d48149cda681c60db13b9"

# Environment variables for local development only
# DO NOT include API keys or tokens here - use Cloudflare Dashboard instead
[vars]
DEFAULT_LLM_PROVIDER = "openai"
DEFAULT_LLM_MODEL = "gpt-4o"

[env.production]
# Define environment variables for production
NODE_ENV = "production"
ENVIRONMENT = "production"
SEARCH_INDEX_ENABLED = "true"
CACHE_TTL = "3600"
MAX_FILE_CHUNK_SIZE = "1048576"

# Preview environment settings
[env.preview]
# Define environment variables for preview
NODE_ENV = "production" 
ENVIRONMENT = "preview"
SEARCH_INDEX_ENABLED = "true"
CACHE_TTL = "3600"
MAX_FILE_CHUNK_SIZE = "1048576"

# Non-sensitive environment variables for preview env
[env.preview.vars]
DEFAULT_LLM_PROVIDER = "openai"
DEFAULT_LLM_MODEL = "gpt-4o"

# Add KV binding to preview environment
[[env.preview.kv_namespaces]]
binding = "POM_BOLT_PROJECTS"
id = "dfe2d0d711d8469298b9ebe3c4d5f596"

[[env.preview.kv_namespaces]]
binding = "POM_BOLT_FILES"
id = "505f6c673aa64c7dba8170749caddbdb"

[[env.preview.kv_namespaces]]
binding = "POM_BOLT_CACHE"
id = "43bb1fedfd1d48149cda681c60db13b9"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "pom_bolt_metadata"
database_id = "f266f4f7-7225-4f31-bcc7-c5010481f263"