# Cloudflare Configuration
# This file configures deployment to Cloudflare Pages and Workers

name = "pom-bolt"

# Enable Node.js compatibility mode for Cloudflare Workers
compatibility_flags = ["nodejs_compat"]

# Set the compatibility date for Cloudflare Workers features
compatibility_date = "2023-09-22"

# Cloudflare Pages configuration
# This is the directory where your built client files are located
# The directory that wrangler pages deploy will use
build = { command = "npm run build", output_dir = "build/client" }

# Enable metrics collection for monitoring
send_metrics = true

# Main D1 database configuration (for local development)
[[d1_databases]]
binding = "DB"
database_name = "pom-bolt-db"
database_id = "3fb97009-64bf-4d52-b7f5-88075da00a87"

# Main KV namespace bindings (for local development)
[[kv_namespaces]]
binding = "PROJECTS_DATA"
id = "caf7bebb43804df4a5b95a1b1da2aaa4"

[[kv_namespaces]]
binding = "POM_BOLT_PROJECTS"
id = "caf7bebb43804df4a5b95a1b1da2aaa4"

[[kv_namespaces]]
binding = "POM_BOLT_FILES"
id = "dbe1a024a7ba47229c2bf76597025c6a"

[[kv_namespaces]]
binding = "POM_BOLT_CACHE"
id = "3fc3d45060c04a2c911853ea7faf63eb"

# Variables for local development
[vars]
NODE_ENV = "development"
DEFAULT_LLM_PROVIDER = "openai"
DEFAULT_LLM_MODEL = "o3-mini"
MULTI_TENANT_ENABLED = "true"
DEFAULT_TENANT_ID = "default"
STRICT_TENANT_VALIDATION = "false"
SEARCH_INDEX_ENABLED = "true"
CACHE_TTL = "300"
MAX_FILE_CHUNK_SIZE = "1048576"

# Production environment configuration
[env.production]
# Define environment variables for production
vars = { NODE_ENV = "production", ENVIRONMENT = "production", SEARCH_INDEX_ENABLED = "true", CACHE_TTL = "3600", MAX_FILE_CHUNK_SIZE = "1048576", MULTI_TENANT_ENABLED = "true", DEFAULT_TENANT_ID = "default", STRICT_TENANT_VALIDATION = "true", DEFAULT_LLM_PROVIDER = "openai", DEFAULT_LLM_MODEL = "gpt-4o" }

# Production-specific D1 database
[[env.production.d1_databases]]
binding = "DB"
database_name = "pom-bolt-db"
database_id = "3fb97009-64bf-4d52-b7f5-88075da00a87"

# Production-specific KV namespaces
[[env.production.kv_namespaces]]
binding = "PROJECTS_DATA"
id = "caf7bebb43804df4a5b95a1b1da2aaa4"

[[env.production.kv_namespaces]]
binding = "POM_BOLT_PROJECTS"
id = "caf7bebb43804df4a5b95a1b1da2aaa4"

[[env.production.kv_namespaces]]
binding = "POM_BOLT_FILES"
id = "dbe1a024a7ba47229c2bf76597025c6a"

[[env.production.kv_namespaces]]
binding = "POM_BOLT_CACHE"
id = "3fc3d45060c04a2c911853ea7faf63eb"

# Preview environment configuration
[env.preview]
# Define environment variables for preview
vars = { NODE_ENV = "production", ENVIRONMENT = "preview", SEARCH_INDEX_ENABLED = "true", CACHE_TTL = "1800", MAX_FILE_CHUNK_SIZE = "1048576", MULTI_TENANT_ENABLED = "true", DEFAULT_TENANT_ID = "preview", STRICT_TENANT_VALIDATION = "false", DEFAULT_LLM_PROVIDER = "openai", DEFAULT_LLM_MODEL = "o3-mini" }

# Preview-specific D1 database with unique ID
[[env.preview.d1_databases]]
binding = "DB"
database_name = "pom-bolt-db-preview"
database_id = "e75ef667-51ed-490c-b2cd-0f6c1f11412f"

# Preview-specific KV namespaces
[[env.preview.kv_namespaces]]
binding = "PROJECTS_DATA"
id = "5e84ef01c7f84a35b86aaa6da7f1c6ad"

[[env.preview.kv_namespaces]]
binding = "POM_BOLT_PROJECTS"
id = "a452d9d552394ea59d3588498689aec5"

[[env.preview.kv_namespaces]]
binding = "POM_BOLT_FILES"
id = "dbe1a024a7ba47229c2bf76597025c6a"

[[env.preview.kv_namespaces]]
binding = "POM_BOLT_CACHE"
id = "3fc3d45060c04a2c911853ea7faf63eb"