name: Deploy to Cloudflare Pages

on:
  push:
    branches: 
      - cloudflare-dep # Your production branch
  pull_request:
    branches:
      - cloudflare-dep

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm build
        env:
          ENVIRONMENT: production
          DEFAULT_PROVIDER: anthropic
          DEFAULT_MODEL: claude-3-5-sonnet-latest
          BETA_ACCESS_CODES: ${{ secrets.BETA_ACCESS_CODES }}
        
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pom-bolt
          directory: ./build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name == 'cloudflare-dep' && 'main' || github.ref_name }}
        
      - name: Set Environment Variables in Cloudflare
        if: github.ref_name == 'cloudflare-dep'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deployment env set --project-name=pom-bolt --branch=main ENVIRONMENT=production DEFAULT_PROVIDER=anthropic DEFAULT_MODEL=claude-3-5-sonnet-latest BETA_ACCESS_CODES=${{ secrets.BETA_ACCESS_CODES }} ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} 